### ISSUE TITLE
Question/Issue

### ISSUE THREAD

**Issue by ziezoo** [nicolonsky/Techblog#1]
Hi,
First of all thanks for the effort. I have a few questions:

1. Get-AzureADDirectoryRole does not seem to list all the built-in roles I do see in the Azure Portal? Moreover role names returned by this applet do not always correspond with the names in the Azure Portal?

2. In which PS1 library can I find [Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]?

Thanks again!

**Comment by nicolonsky** [comment]
Hi @ziezoo 

The ```Get-AzureADDirectoryRole``` cmdlet only returns directory roles which have been assigned at least once (then it will be returned by the cmdlet). ```Get-AzureADDirectoryRoleTemplate``` returns all the available ones. Find more info here: https://github.com/Azure/azure-docs-powershell-azuread/issues/245#issuecomment-485398779

The type ```[Microsoft.Open.Azure.AD.CommonLibrary.AzureSession]``` comes with the AzureAD PowerShell module.

Hope this answers you question & helps?

**Comment by ziezoo** [comment]
Hi @nicolonsky 
Thanks ! Yes I already found the GetAzureADDirectoryRoleTemplate cmdlet which combined with your script gives me what I want.
Another question: this AzureAD module is not available yet in the Az module is it? I could not found any Az equivalents such as Get-AzADDirectoryRole and Get-AzADDirectoryRoleTemplate, Get-AzADDirectoryRoleMember?

**Comment by nicolonsky** [comment]
The AzureAD module is for all the Azure Active Directory parts whereas the Az module is to manage resources in Azure. These modules have really different intentions.
