### ISSUE TITLE
Create Desktop Icon producing broken link files when using environment variables

### ISSUE THREAD

**Issue by im-fabian** [nicolonsky/Techblog#10]
Using this as an install command:

%windir%\sysnative\windowspowershell\v1.0\powershell.exe -ExecutionPolicy Bypass -Windowstyle hidden -file "CreateDesktopIcon.ps1" -ShortcutTargetPath "$env:HOMEDRIVE$env:HOMEPATH\foldername\foldername" -ShortcutDisplayName "this&that Workspace"

which is a synced sharepoint site produces a broken link on the desktop (doesn't have target at all). Using the script as the user works just fine so just the intune deployment is broken when using environment variables.

**Comment by nicolonsky** [comment]
Please make sure to deploy the script with the option to run under user context, otherwise these environment variables aren't available.

**Comment by im-fabian** [comment]
Thanks für your reply. But the option is set to install it within user context:
<img width="563" alt="intune-create-shortcut_png" src="https://user-images.githubusercontent.com/31921275/140910029-bc8efd9b-1644-4cc6-9ac5-a258839da086.png">

For explination:
I tried both powershell.exe and %windir%\sysnative\windowspowershell\v1.0\powershell.exe as recommended in the tutorial. Both produce the same broken link.

**Comment by nicolonsky** [comment]
Did you try to specify the windows environment variables instead of the PowerShell ones? E.g. %HOMEDRIVE%. Haven't used the script recently but I guess this could be the issue as IME doesn't parse the PowerShell environment variable
