### ISSUE TITLE
Export-EndpointSecurityTemplates does not export all settings

### ISSUE THREAD

**Issue by wiseleaf23** [nicolonsky/Techblog#11]
Whilst implementing your script in our environment, I was seeing that a lot of BitLocker settings seemed to be missing in the JSON variable, for example the `deviceConfiguration--windows10EndpointProtectionConfiguration_bitLockerSystemDrivePolicy`. Upon investigation I noticed that this was resolved with removing the ` | Where-Object { $null -eq $_.value }` where settingsDelta is declared in the object.

I found that without checking for null values, there did not seem to be any empty values in the JSON (in my example). I fixed this in our implementation, but this may be useful information for you.

**Comment by nicolonsky** [comment]
Thanks @wiseleaf23 this is definitely a bug 🤦‍♂️
