### ISSUE TITLE
IntuneShortcut

### ISSUE THREAD

**Issue by Q33NY1** [nicolonsky/Techblog#4]
IntuneShortcut

it works only for 1 of the 3 shortcuts. Is there anything we can do?

**Comment by nicolonsky** [comment]
That's not a really helpful description of an issue. Probably related to the availability of the shortcut target and/or the context you're executing the Win32 app.

**Comment by Q33NY1** [comment]
So what happens is: I have 3 shortcuts, helpdesk, every_portal and Office35_Portal. If the system adds the 1st one it doesn't add the other 2. If I take the 1st one out it adds OK the other 2. I've just recreate the shortcut of the 1st one and wait for deployment but it seems now that it won't add any of the shortcuts....

**Comment by Q33NY1** [comment]
correction, it added again only the 1st shortcut....

**Comment by nicolonsky** [comment]
Sounds like an issue with the detection. Double-check your detection rule configuration

**Comment by nicolonsky** [comment]
You can find all the related details in the Intune Management Extension log `%Programdata%\Microsoft\IntuneManagementExtension\Logs\IntuneManagementExtension.log`

**Comment by Q33NY1** [comment]
Detection rule, I forgot to change the name of the shortcut. I will run it again and let you know.

**Comment by Q33NY1** [comment]
All working perfect now. :) thank you
