### ISSUE TITLE
IntuneShortcut

### ISSUE THREAD

**Issue by Q33NY1** [nicolonsky/Techblog#5]
HI, me again, I've tested the script and it works perfect after I've corrected my mistake in the detection script but only on one user. The second user that logs on the device get's no shortcut diploid. The shortcut app is assigned to computers no to users. If you don't mind helping with this again. Thx :)

**Comment by Q33NY1** [comment]
I don't know if it makes any difference but the user that works is global admin, the other just normal user. At 1st login of the normal user I got some notifications about the shortcuts where it said failed.

**Comment by Q33NY1** [comment]
[IntuneManagementExtension.log](https://github.com/nicolonsky/Techblog/files/5339829/IntuneManagementExtension.log)
This is the log file just after the failed install.

**Comment by Q33NY1** [comment]
![20201007_121216](https://user-images.githubusercontent.com/72378908/95323645-69ea2000-0896-11eb-9adc-88b725ac78e9.jpg)
And here is the error message I get in notification panel.

**Comment by nicolonsky** [comment]
Install command looks fine and works `powershell.exe -ExecutionPolicy Bypass -file "CreateDesktopIcon.ps1" -ShortcutTargetPath "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" -ShortcutDisplayName "Every_Portal" -IconFile "https://iconarchive.com/download/i49237/mag1cwind0w/akisame/Tools.ico" -ShortcutArguments "https://auth.every.education/Account/Login"`

IME log shows the following error:
![image](https://user-images.githubusercontent.com/32899754/95349169-13dda280-08bf-11eb-9850-c6a8aa177589.png)

This error translates to;

```
ERROR_ACCESS_DISABLED_BY_POLICY

1260 (0x4EC)

This program is blocked by group policy. For more information, contact your system administrator.
```

Probably you have configured some software restrictions policies which block PowerShell.

**Comment by Q33NY1** [comment]
Mate you are the best, Indeed, we've blocked powershell (we are a school and you know teenagers trying stuff), is there a way we can baypass this to run as system user instead of run on the local user?

**Comment by nicolonsky** [comment]
Yes you can control this behaviour here:
![image](https://user-images.githubusercontent.com/32899754/95350430-6e2b3300-08c0-11eb-9813-f3f9c84b894c.png)
But then the shortcut get's created on the allusers desktop.

**Comment by Q33NY1** [comment]
that's exactly what I need :) I will give it a try and let you know if it worked. Sorry about the delay but this will be tomorrow most likely.

**Comment by Q33NY1** [comment]
Just teste it now and it works as designed :) Thank you once again.
